name: scipy-2021-streamlit
channels:
  - conda-forge
dependencies:
  - scikit-learn=0.24.2
  - python=3.8
  - shap=0.39.0
  - streamlit=0.84.0
  - pandas=1.3.0
  - pip=21.1.3
  - pip:
    - anchor-exp==0.0.2.0
